### PR TITLE
Class built for the new Sequence Coordinate Server

### PR DESCRIPTION
**Pull request by bioinsilico**
Class building for the new Sequence Coordinates schemas. Some executions diverge from the std procedure to keep enumerated values as enums.

Ping @josemduarte @JonStargaryen

### CODE REVIEW

**Comment by bioinsilico** [comment]
Included adjustments to build local schemas

Ping @josemduarte

**Review by josemduarte — APPROVED** [review]
LGTM thanks. We are planning a new release on Thursday. If you merge it, this will go with it.

**Comment by bioinsilico** [comment]
@valasatava happy with this PR?

**Review by valasatava — APPROVED** [review]

**Comment by valasatava** [comment]
> @valasatava happy with this PR?

Yes, thank you!

**Pull request merged**
